version: "3.8"

services:
  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"   # Interface web
      - "15692:15692"   # Prometheus metrics endpoint
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

# api1:
#   build: ../api1
#   ports:
#     - "8080:8080"

# api2:
#   build: ../api2
#   ports:
#     - "8081:8081"

# api3:
#   build: ../api3
#   ports:
#     - "8082:8082"
volumes:
  prometheus_data:
  grafana_data:
  rabbitmq_data:
