global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files: []

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
        labels:
          app: "prometheus"

  - job_name: "rabbitmq"
    static_configs:
      - targets: ["rabbitmq:15692"]
        labels:
          app: "rabbitmq"

  - job_name: "api1"
    static_configs:
      - targets: ["api1:8080"]

  - job_name: "api2"
    static_configs:
      - targets: ["api2:8081"]

  - job_name: "api3"
    static_configs:
      - targets: ["api3:8082"]
